### ISSUE TITLE
Add description to C4 level diagram 

### ISSUE THREAD

**Issue by Alexshailiha** [kmachura/help-chef#14]
Short description of visualization of help-chef software architecture

**Comment by Alexshailiha** [comment]
C4 level model diagram stands for context, containers, components, and code. It is a diagram that shows a hierarchical set of software architecture and is a great tool to communicate the planning process of a software system.

**Comment by adamkowalsky11** [comment]
Help-chef project is beeing created using many programming languages and technologies.
Backend of the application is beeing implemented in Java. Spring Framework is responsible for business side of the system and enables double sided communication with H2 database.
Connection with server follows with REST API architecture style. Web application is beeing created using JavaScript Framework - Angular.
