### ISSUE TITLE
Select color for the main pge

### ISSUE THREAD

**Issue by wdubel** [kmachura/help-chef#15]
Choose the right color palette from colorhunt.co

**Comment by Alexshailiha** [comment]
How many colors do we want to include on the site? Three 一 a primary, a secondary, and a background color? By looking at our logo, white as a primary color? It is always timeless and matches well with others. What do you think about this one: https://colorhunt.co/palette/1684a709a599f6ec72f6f6f6

**Comment by Alexshailiha** [comment]
Or this green #257f69;? We could match it well with black and white.

**Comment by wdubel** [comment]
Maybe this palette.  I think it's interesting too.
https://colorhunt.co/palette/ede9d5e7ab9adf7857617143

**Comment by Alexshailiha** [comment]
Doesn't look bad but it would clash with our black and white logo. What about this one: https://colorhunt.co/palette/222831393e4600adb5eeeeee. Not only, it has white and black, but it is also one of the most popular ones on the website.

**Comment by Alexshailiha** [comment]
So, we shall go with this one https://colorhunt.co/palette/222831393e4600adb5eeeeee ? Thumbs up if you agree.
