### ISSUE TITLE
Create UML diagrams for the project Help Chef

### ISSUE THREAD

**Issue by kmachura** [kmachura/help-chef#3]
Create UML diagrams in Visual Paradigm - https://www.visual-paradigm.com

**Comment by Alexshailiha** [comment]
Add the UML diagrams to Readme.md

**Comment by adamkowalsky11** [comment]
![Use case diagram ZJO](https://user-images.githubusercontent.com/55921722/226111280-cf9f8f2e-c37b-423d-ae8a-6f97abec5c97.jpg)

**Comment by adamkowalsky11** [comment]
Class diagram
![Class Diagram ZJO](https://user-images.githubusercontent.com/55921722/226114808-6be7eff3-ff13-439c-8856-abe592e5bc79.jpg)

**Comment by Alexshailiha** [comment]
A use case diagram is a UML diagram that shows us in the form of scenarios how a system or software interacts with individuals, organizations, or external systems carried for the purposes of this diagram the name of actors. It transmits how the actor uses the system to achieve a specific goal. It doesn't implement details, attributes, and user values. Without an actor, creating a use case diagram would be impossible as the main goal is to show how to use the system. Thus, it allows you to designate programmer, the goals that a given software user will want to achieve. These diagrams are used to supplement more detailed documentation. In this case, it shows how a potential user or a person with an already-created account can look for, add, delete, update, or review recipes on Help Chef.

**Comment by adamkowalsky11** [comment]
Activity diagram
![Activity Diagram ZJO](https://user-images.githubusercontent.com/55921722/226203864-cab3cd57-3b53-4848-b6d3-e09411b5e104.jpg)
