### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by adamkowalsky11** [kmachura/help-chef#30]
Working docker

**Comment by adamkowalsky11** [comment]
Instruction:
1. Make sure that you have installed and configured Docker Desktop and Git on your computer
2. Run cmd/terminal/powershell
3. Clone project from Github by entering following script into your console:
git clone https://github.com/kmachura/help-chef.git
4. Enter following script into your console:
cd help-chef
6. Enter following script into your console::
git checkout origin/DockerizeProject
8. Enter following script into your console:
docker-compose -f docker-compose.yml up

You can reach app by entering following links into your browser:
backend: http://localhost:9000/
frontend: http://localhost:8082/

**Comment by adamkowalsky11** [comment]
Checked on two computers and both checks ended positive - I was able to reach backend and frontend of the application

**Comment by Alexshailiha** [comment]
Well done! No bugs that I can see.

**Comment by adamkowalsky11** [comment]
Thank you for confirmation :D
